config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root "jobs#index"

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]
	def index
		@jobs = Job.all.order("created_at DESC")
	end

	def show
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "New"
		end
	end

	def edit
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "Edit"
		end
	end

	def destroy
		@job.destroy
		redirect_to root_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url)
	end

	def find_job
		@job = Job.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: { class: 'form-horizontal'}) do |f|
	= f.input :title, label: "Job title"
	= f.input :description, label: "Job description"
	= f.input :company, label: "Your company"
	= f.input :url, label: "Link to job"
	%br/
	= f.button :submit

app/views/jobs/edit.html.haml
%h1 Edit job

= render 'form'

= link_to "Back", root_path

app/views/jobs/index.html.haml
- @jobs.each do |job|
	%h2= link_to job.title, job
	%p= job.company

= link_to "New job", new_job_path

app/views/jobs/new.html.haml
%h1 New job

= render 'form'

= link_to "Back", root_path

app/views/jobs/show.html.haml
%h2= @job.title
%p= @job.description
%p= @job.company

= link_to "Home", root_path
= link_to "Edit", edit_job_path(@job)
= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>